#ifndef _CONTROLLER_H
#define _CONTROLLER_H

#include "main.h"
#include "stdint.h"
#include "FOC.h"

extern MOTOR_HandleTypeDef Motor;
extern uint32_t ADC1_value[4];
extern uint32_t ADC2_value[2];

typedef enum
{
    IDIE_STATE,
	OPEN_LOOP,
	SPEED_CLOSE_LOOP,
    SPEED_CURRENT_CLOSE_LOOP_SENSORLESS,
    SPEED_CURRENT_CLOSE_LOOP_OVERMODU_FW,
} FOC_MODE_TYPE;

typedef enum
{
    WARNING_STATE,
	ADC_CALIBRATION,
	RS_IDENTIFY_VOLTAGE_DESIGM,
	PARAMETER_IDENTIFY_Rs,
	PARAMETER_IDENTIFY_L,
	PARAMETER_IDENTIFY_Flux,
	PARAMETER_IDENTIFY_J,
	FOC_RUN,
}STSTEM_STATE_TYPE;

#endif
